### PR TITLE
Added ability to set the objects position in ModelView - space ( Glob…

### PR DESCRIPTION
**Pull request by VarolOkan**
I think this small change may be useful for everyone

### CODE REVIEW

**Comment by andresoviedo** [comment]
Hi Varol.  Thanks for your contribution.

Would you please help me understand what's the difference between the current model position vs global position?

**Comment by VarolOkan** [comment]
The local position is after your apply the rotation matrix. That is you use 
the object coordinate system.

The global position is applied on top of the  modelview matrix, thus you 
move the model in world coordinates.

I wanted a rotating sphere at position X,Y,Z. That was not possible to do 
before, unless you moved all objects in the scene which is not what I wanted .

Let me know if this makes sense.

Cheers

BTW, more to come wrt sceneloader. I hope I get some work on this done over 
the weekend

On October 3, 2018 2:51:10 PM Andres Oviedo <notifications@github.com> wrote:
> Hi Varol. Thanks for your contribution.
> Would you please help me understand what's the difference between the 
> current model position vs global position?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by VarolOkan** [comment]
Hey

I am continuing to use and enhance your code.

However I hit a snag and can't seem to progress atm.

I want to creat a set of 2D buttons ( Aka sprites ) but I can't seem to 
load a texture into the object ( 2 triangles ) and display it accordingly.

I looked at your sample code as to how the textured cubes are generated but 
there seems to be some magic I am missing.

Do you have an example on how to load a PNG from the resources ( e.g. 
R.drawable.test ) into a texture, including transparency and create a 
Object3DData from it ?
Note, to resolution is 64x64 pixels in RGBA - format.

Thanks



On October 3, 2018 14:51:10 Andres Oviedo <notifications@github.com> wrote:
> Hi Varol. Thanks for your contribution.
>
> Would you please help me understand what's the difference between the 
> current model position vs global position?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by VarolOkan** [comment]
Hey,

I finally figured it out and made some more changes on my branch.

Thanks.

**Comment by andresoviedo** [comment]
Many thanks @VarolOkan   I will merge changes as soon as possible

**Comment by VarolOkan** [comment]
Hey,

FYI, I found some issues in the code wrt FloatBuffer asReadOnlyBuffer esp 
in CollissionDetection

It took me two days to teach this down, as it was working on my Samsung S5 
but not for my Nexus6.

I am wondering why this function is used at all. Sorry, I am more of a C++ 
type rather than Java and a lot of the 'fluff' I see does not make a lot of 
sense to me but as long as it works ...
So if you don't see any issuesi would like to go through the code and throw 
all asReadOnlyBuffer function calls out.


From:https://hub.jmonkeyengine.org/t/jme3-1-rendering-failure-specifically-for-android-7-nougat/39018/24
The explanation is as follows. The problem is in converting vertex buffer 
to a read only buffer with the FloatBuffer.asReadOnlyBuffer method.

The new buffer obtained will contain strange coordinate values for the 
vertices. Therefore, if the position of the vertex is incorrect, the 
rendering is scrambled.

The data indicates that it is a bug with the java.nio lib for android 7.

It makes sense because as already mentioned by rickard from the Android 7 
the adopted Java implementation changed to OpendJDK.


On October 13, 2018 6:46:21 AM Andres Oviedo <notifications@github.com> wrote:
> Many thanks @VarolOkan I will merge changes as soon as possible
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by VarolOkan** [comment]
Andre

I have just published the initial version of my improved app which is using 
your lib.
http://www.softwaresamurai.org
https://play.google.com/store/apps/details?id=com.aqamob.cpuinformation

Please give it a try and let me know what you think.

Thanks.

Varol :)

On October 13, 2018 6:46:21 AM Andres Oviedo <notifications@github.com> wrote:
> Many thanks @VarolOkan I will merge changes as soon as possible
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by andresoviedo** [comment]
closing this pull request as too old and obsolete
a new pull request should be made in case the acceptance criteria is not met

**Pull request closed without merging**
